"""Verify Alembic migrations apply, roll back, and match the models (no drift)."""

from __future__ import annotations

import pytest
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected

pytestmark = pytest.mark.integration


def _reset_to_base(config: Config) -> None:
    """Downgrade to base to ensure a clean slate before upgrading.

    The db_session fixture uses SQLAlchemy create_all/drop_all, which does not
    touch alembic_version.  If integration tests ran first they leave
    alembic_version at an intermediate revision with no real tables, so a
    subsequent upgrade head would skip early migrations and fail trying to
    ALTER tables that were never created.  Downgrading to base (a no-op when
    already at base) eliminates that race.
    """
    command.downgrade(config, "base")


def test_migrations_apply_and_match_models() -> None:
    config = Config("alembic.ini")
    _reset_to_base(config)
    command.upgrade(config, "head")
    try:
        # Raises AutogenerateDiffsDetected if the models drift from the migrated schema.
        command.check(config)
    finally:
        command.downgrade(config, "base")


def test_migration_check_is_clean() -> None:
    config = Config("alembic.ini")
    _reset_to_base(config)
    command.upgrade(config, "head")
    try:
        command.check(config)
    except AutogenerateDiffsDetected as exc:  # pragma: no cover - failure path
        command.downgrade(config, "base")
        pytest.fail(f"Models drifted from migrations: {exc}")
    else:
        command.downgrade(config, "base")
