"""add tool metadata

Revision ID: 8e1814737b0a
Revises: 8134eced0fe3
Create Date: 2026-06-30 15:21:39.298974

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "8e1814737b0a"
down_revision: str | None = "8134eced0fe3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tools", sa.Column("description", sa.Text(), nullable=True))
    op.add_column("tools", sa.Column("image_tag", sa.String(length=255), nullable=True))
    op.add_column("tools", sa.Column("default_timeout", sa.Integer(), nullable=True))
    op.add_column(
        "tools",
        sa.Column("supports_batch", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tools", "supports_batch")
    op.drop_column("tools", "default_timeout")
    op.drop_column("tools", "image_tag")
    op.drop_column("tools", "description")
    # ### end Alembic commands ###
