"""add quota settings

Revision ID: a787a12a5023
Revises: 8e1814737b0a
Create Date: 2026-06-30 16:22:08.031165

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a787a12a5023"
down_revision: str | None = "8e1814737b0a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "system_settings",
        sa.Column("standard_max_concurrent_runs", sa.Integer(), server_default="3", nullable=False),
    )
    op.add_column(
        "system_settings",
        sa.Column("power_max_concurrent_runs", sa.Integer(), server_default="12", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("system_settings", "power_max_concurrent_runs")
    op.drop_column("system_settings", "standard_max_concurrent_runs")
    # ### end Alembic commands ###
